#!/bin/bash

rm -rf ./bcash
rm -f ./bob/public/bcash.js
rm -f ./bob/public/bcash-worker.js

git clone https://github.com/bcoin-org/bcash.git
cd ./bcash
git checkout 8621c38c5d9f498da1abb355d4a23b21db0e3764
npm install
npm run webpack-browser
cd ..

cp ./bcash/browser/bcash.js ./bob/public/bcash.js
cp ./bcash/browser/bcash-worker.js ./bob/public/bcash-worker.js
