#!/bin/bash

rm -rf ./bcoin
rm -f ./app/public/bcoin.js
rm -f ./app/public/bcoin-worker.js

git clone https://github.com/bcoin-org/bcoin.git
cd ./bcoin
git checkout f00ed98eead4583e6b1020dbff9c4bf2d3a527de
npm install
npm run webpack-browser
cd ..

cp ./bcoin/browser/bcoin.js ./app/public/bcoin.js
cp ./bcoin/browser/bcoin-worker.js ./app/public/bcoin-worker.js
