#!/bin/bash

apikey=`openssl rand -hex 32`

sed "s/changeme/$apikey/g" ./config.example.json > ./config.json
sed -i "s/TESTNET\": true/TESTNET\": false/g" ./config.json
echo $apikey

sed "s/changeme/$apikey/g" ./docker/bcoin.service > /etc/systemd/system/bcoin.service
sed -i "s/testnet/main/g" /etc/systemd/system/bcoin.service
sed "s/changeme/$apikey/g" ./docker/bcash.service > /etc/systemd/system/bcash.service
sed -i "s/testnet/main/g" /etc/systemd/system/bcash.service
cp ./docker/bobwallet.service /etc/systemd/system/bobwallet.service

sh ./docker/build_bcoin
sh ./docker/build_bcash
sh ./docker/build_server

systemctl daemon-reload
systemctl enable bcash
systemctl enable bcoin
systemctl enable bobwallet
systemctl start bcash
systemctl start bcoin
systemctl start bobwallet

echo DONE
