#!/bin/bash

apikey=`openssl rand -hex 32`
sed "s/changeme/$apikey/g" ./config.example.json > ./config.json
sed -i "s/BCOIN\": true/BCOIN\": false/g" ./config.json
echo $apikey

sed "s/changeme/$apikey/g" ./docker/bcash.service > /etc/systemd/system/bcash.service
cp ./docker/bobwallet.service /etc/systemd/system/bobwallet.service

sh ./docker/build_bcash
sh ./docker/build_server

systemctl daemon-reload
systemctl enable bcash
systemctl enable bobwallet
systemctl start bcash
systemctl start bobwallet

echo DONE
